spring:
  application:
    name: vehicle-routing-sim

# 地图对象存储路径
map:
  object:
    filepath: "classpath:map/map_object/map_object.ser"
  file: "classpath:map/map_image.bmp"

car:
  nums: 5

passenger:
  nums: 3

# 服务器端口
server:
  port: 8888

  # 设置日志编码
logging:
  charset:
    console: UTF-8
    file: UTF-8